travis:
  secure:
    BINSTAR_TOKEN: ILTosEe8RoN4eAMihI/kjahG43Q8jRaXmtQHME4lCi8PhY+IqLJScBGY9TnO+slG4eh8O8f6h5Ixem/6R/7RD6ajJMdBMxrdDfgy5/6dsTMumHqPB1H+ED7+7h1/KEeckhEoqm5TvTRRYEplnmT1PNUhtcOKxcbtF78RKiOz0TioZyD7toywvz0Dqb5j8i4+28II1rSw60aIoo6UR1km72Q93/gwKD6xwMw3GcGUrxYJZkNdnrBjGjAr5xMkRtdj4tkBYnPauahqX4JSGqSoeY69A28zwCCO+kbsMCbShMsZt18sivBUu6uoFQAolQCuQCAFqnXW/cVszt/1PtJxbtqv3ECVBh+zsWhMjlnJmaDrJqQ+ck5SM81FUZX1Cnl0n/O2K5lHqwTk34aUS3bRFQ/gIHF6cfm+0ubgc0bw5bGPHVvyF1XeaZ+lkbuIu2/2WQ6+aSR5a+mbNMPgtOR0wz4fAndNVmzZmvxEwCf7SMe25PF3uM0dy6HYOXpGnYfNTz1zKhp3DzQBfu80FR8tEbWYnRB+KVH/dZ13qVRrK9yobuPWyio2Bs3KLcBWE8wubM1QGbbpJj+0HaixXMAqugX+ShYvNyKovw8Ch3Oq7i2mibK8DgYM6OAdYnv0M2CJORVd68iJusrQm8xOt2pBdg5vIOnHrqVc+VPlWtlTTdE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
