travis:
  secure:
    BINSTAR_TOKEN: B/nCb3owz1G7pQj+LL2TO0fuvSJ80Liu9xmI+xK/nnM4wV6+vP1TYXe0NQmzJ31Mwq5pRmaYe5oO7NIK+jJREfSBdboewNDTPqZxapNcwSvyBLsek+5ssYMT0hFaXp98ZYuHk0U1wBy7GAzni88X+OzQw1ZKGtdR5/rZokJTZtEfKJnCl5ZKPUqxxVD2mFkOepSC+67YWQEV4MI0yC9/p1ie4ma0CmMJjmyfBMLDwf6za8lHW7pq5ahnu5/4xofU7JsGl7T11Ga8nJ/JVOF2vJguDXgp/IVgKpfYMoya5VMA3WiM4eDDQkLgc4DI0/uu81X1SHA9gVafP5LF1k4lwLhd/YvQOomo2o/q9fDNzvoCKVbVYuWp/zWNvTA4OfTlgZQsBoPvZVytY9Rz/ArXQQOkdp/2LvEnmyAIHtGjPDbwxcGTNQtZSdHb+49qx5iHJXiTfeMg0Ig8swUihclyHsi75vu7SOwxnA6R9vNlrxUN3AVsjF7NISMSizhmpnawVUHU7RTlyRDWcPJzmVFsdxqFTWilfcPQzBKM60HkKET2/5+AtaZXwUwJJyrJ8047Zs7pQ1pX2iwzi5Firi2BQWL47LLn6zLHy/BI2xD6Yx7gXFECRpqQA9y9MSJizpIt7qFwUymsw7i977XGwzS9NMkkQm1yiVIDWAY8YdUYaGo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
