travis:
  secure:
    BINSTAR_TOKEN: Rg8iLU8eq9MPEXQ1Ako8YXc/8bAq3m+QtMXtnpRv4gRv6cWzW1AL8ycYKLVlsHcrha+1j7zIxrS1Enk/eBFDIjaHOD36RqrY554WZ3eAEFXFdBi0H49Dbd1feVw51krULpixmruLJ2YxzhOUYQEat1mCdbLsEKXB6GhUWOzqtKmxMwpgv19TbUn1qESkvs+Cksq2bdWYRZ11g9EsDd0FuPbG01o7qRXvmJuPOe8XWZpzARO/YplYuymeX1l6WfRKslQYbyugdubkCb3FZZmayD6V99wDdKm0KvDzPKRhoUC63LwxBSYKrc9deUSnQmdxlybe1fQRNKveIxvHm+BksArcOf+6uwan+H4P77p3Sqzox8vwcmJqA7xXfbHxOsXSKeUNJ1tuoNuwp8nxCaM7+QGE9zbK8YBAt+uKq4iqMAPr2iqdX20mzDgIBxiE8j39WHKEuQEa57N8j0fzt0hZ6kWpnGdX2sYTDZJb0yy903tPLouOqYqVNhtElWvfRwbvKF9Top1vYGb9Hsa0DksTBLnn0yjw+qGrwwYJfw4xWPgI1tZk088gqm1x2uljxIrJFpyeTjHKiNLKDFM8whb+alk7+AMzzOMsqQD4xuT9AuJ2SOcJiXHMuja9iBp6m/4FMIAnTl9loQr7JMNYUEkA19Zd/nluc1UFGI6vxFsThtA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
